### ISSUE TITLE
Dark theme support

### ISSUE THREAD

**Issue by edmondsiu0** [MortalHappiness/sn-tui.editor#1]
Hi, thank you for the editor, great work and I love it! 

Is it possible for the editor to support themes, especially dark mode on SN? 

### Example of light theme 

> <img width="575" alt="image" src="https://github.com/MortalHappiness/sn-tui.editor/assets/37211844/cc2129ef-517f-4ac1-bb2f-7f90ed1feb76">  

In this example the text is dark rendered on light background, which is expected. 

### Example of dark theme
> <img width="575" alt="image" src="https://github.com/MortalHappiness/sn-tui.editor/assets/37211844/aba975dd-a877-4c45-b3f6-4f92644a9d01">

In this example the text is still dark and rendered on themed background, which makes the text unreadable.  
(Highlighted to demonstrate text is still there.)

**Comment by MortalHappiness** [comment]
Supported in version 0.2.0.
![image](https://github.com/MortalHappiness/sn-tui.editor/assets/47914085/49dfcce4-83f7-4835-b6a6-b1679e227886)
